@startuml Implementation
top to bottom direction
!define PAGE artifact
!define PHP process
!define DASHBOARD interface
!define UC usecase

' Pages and PHP Scripts
PAGE "Log-in" as login
PHP "process_login.php" as process_login
DASHBOARD "Dashboard" as dashboard
PAGE "Registration" as registration
PAGE "Forgot Password" as forgot_password
PAGE "Games" as games
UC "View game schedule" as view_schedule_games
UC "Update game stats" as manage_game_stats
UC "Create match" as schedule_new_game
PAGE "Teams" as teams
UC "View statistics" as view_team_stats
UC "Delete team" as delete_team
UC "Create team" as add_team
PAGE "Account Management" as account_management
UC "Update profile" as update_profile
PAGE "Players" as players
UC "View statistics" as view_player_stats
PHP "db.php" as db_config
PHP "session_check.php" as session_check
PAGE "User Management" as user_management
UC "Assign user role" as assign_user_role
UC "Assign player to team" as assign_player
UC "Remove player from team" as remove_player

' Page Flow
login --> process_login : "User submits credentials"
login --> registration
login --> forgot_password
process_login --> dashboard : "Valid credentials"
process_login --> login : "Invalid credentials"
process_login <--> db_config : "Connect to database"
dashboard -[dashed]-> session_check : "Check session"
session_check --> games
games --> view_schedule_games : "Everyone"
games --> manage_game_stats : "Statistician"
games --> schedule_new_game : "League manager"
session_check --> teams
teams --> view_team_stats : "Everyone"
teams --> delete_team : "League manager"
teams --> add_team: "League manager"
session_check --> account_management
account_management --> update_profile : "Account holders"
session_check --> players
players --> view_player_stats : "Everyone"
session_check --> user_management
user_management --> assign_user_role : "League manager"
user_management --> assign_player : "League manager"
user_management --> remove_player : "League manager"

' Legend '
legend top left
|= Process |= Description |
| process_login.php | Checks user credentials |
| db.php | Database connection configuration |
| session_check.php | Verify that user is logged in. Runs before each page load. |
endlegend
@enduml