@startuml usecases
' Config '
left to right direction
skinparam ArrowThickness 1.3
!define league_manager_color #ff595e
!define statistician_color #f48c06
!define coach_color #8ac926
!define player_color #1982c4
!define fan_color #6a4c93

' Actors
package "Account Required" {
  package "Management" {
    actor "League Manager" as league_manager league_manager_color
    actor "Statistician" as statistician statistician_color
    actor "Coach" as coach coach_color
  }
  actor "Player" as player player_color
}

actor "Fan" as fan fan_color

' Use cases '
package "System" {
  package "League Management" {
    usecase "Assign user role" as assign_user_role
    usecase "Assign coach to team" as assign_coach
    usecase "Assign player to team" as assign_player
    usecase "Remove player from team" as remove_player
    usecase "Create match" as create_match
    usecase "Create team" as create_team
    usecase "Delete team" as delete_team
  }
  package "Team Management" {
    usecase "Change player position" as change_player_position
    usecase "Email all players in roster" as email_players
    usecase "Email individual player" as email_player
  }
  package "Statistics Management" {
    usecase "Update game stats" as update_game_stats
    usecase "Update player stats" as update_player_stats
  }
  package "Profile Management" {
    usecase "Update profile" as update_profile
  }
  package "Everyone" {
    usecase "View statistics" as view_stats_report
    usecase "View game schedule" as view_game_schedule
    usecase "View league standings" as view_standings
  }
}

' Relationships '
league_manager --[league_manager_color]> assign_user_role
league_manager --[league_manager_color]> assign_coach
league_manager --[league_manager_color]> assign_player
league_manager --[league_manager_color]> remove_player
league_manager --[league_manager_color]> view_stats_report
league_manager --[league_manager_color]> view_game_schedule
league_manager --[league_manager_color]> view_standings
league_manager --[league_manager_color]> update_profile
league_manager --[league_manager_color]> create_match
league_manager --[league_manager_color]> create_team
league_manager --[league_manager_color]> delete_team
coach -[coach_color]> change_player_position
coach -[coach_color]> view_stats_report
coach -[coach_color]> view_game_schedule
coach -[coach_color]> view_standings
coach -[coach_color]> email_players
coach -[coach_color]> email_player
coach -[coach_color]> update_profile
player --[player_color]> view_stats_report
player --[player_color]> view_game_schedule
player --[player_color]> view_standings
player --[player_color]> update_profile
statistician --[statistician_color]> update_game_stats
statistician --[statistician_color]> update_player_stats
statistician --[statistician_color]> view_stats_report
statistician --[statistician_color]> view_game_schedule
statistician --[statistician_color]> view_standings
statistician --[statistician_color]> update_profile
view_stats_report <-[fan_color]- fan
view_game_schedule <-[fan_color]- fan
view_standings <-[fan_color]- fan
@enduml